config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  get'terms' => 'pages#terms'
  get'about' => 'pages#about'
  resources :articles do
    resources :comments
  end

  resources :contacts, only: [:new, :create], path_names: { :new => '' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end




end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create]
 

  def new

  end
  def show
    @article = Article.find(params[:id])
  end

  def index
    @article = Article.all
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

   def destroy 
      @article = Article.find(params[:id])
      @article.destroy

      redirect_to articles_path
   end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

 private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

     before_action :authenticate_user!, :only => [:new, :create]
    def create
        @article = Article.find(params[:article_id])
        @article.comments.create(comment_params)


        redirect_to article_path(@article)
    end


private

def comment_params
  params.require(:comment).permit(:author, :body)
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
       render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms

  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>New article</h1>


<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<% @article.each do |article| %>
  <h2>
    <%= article.title  %>
  </h2>
  <p><%= article.text %></p>
 
  <p>
    <%= link_to 'Show', article_path(article) %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
  <hr>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>


  <%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.text %></p>

<%= form_for([@article, @article.comments.build]) do |f| %>
 


<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.author %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
  <hr>
<% end %>



 <p>
 <%= f.label :author %><br>
 </p>
    <p>  <%= f.text_field :author %></p>
  
 <p> <%= f.label :body %><br></p>
 <p> <%= f.text_area :body %></p>
   
   

    <%= f.submit %>

  <% end %>

app/views/contacts/create.html.erb
<h1>Thanks!</h1>

app/views/contacts/new.html.erb
<h1>Contact Us</h1>


<%= form_for :contact, url: contacts_path do |f| %>
<% if @contact && @contact.errors.any? %>
    <p>
      <ul>
      <%= @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </p>
    <% end %>



  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>
  <p>
    <%= f.submit 'Send message'%>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<% if user_signed_in? %>
 You logined us: <strong> <%= current_user.username %> </strong>| <%= link_to 'Sing Out', destroy_user_session_path, method: :delete %>   
<% else %>
  <%= link_to 'Sing In', new_user_session_path %>
<% end %>




  

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/terms.html.erb
<h1>Terms</h1>